- project:
    name: theopenlab/terraform-provider-openstack
    check:
      jobs:
        - terraform-provider-openstack-unittest
        - terraform-provider-openstack-acceptance-test
    recheck-mitaka:
      jobs:
        - terraform-provider-openstack-acceptance-test-mitaka
    recheck-newton:
      jobs:
        - terraform-provider-openstack-acceptance-test-newton
    recheck-ocata:
      jobs:
        - terraform-provider-openstack-acceptance-test-ocata
    recheck-pike:
      jobs:
        - terraform-provider-openstack-acceptance-test-pike
    recheck-trove:
      jobs:
        - terraform-provider-openstack-acceptance-test-trove
    recheck-designate:
      jobs:
        - terraform-provider-openstack-acceptance-test-designate
    recheck-lbaas:
      jobs:
        - terraform-provider-openstack-acceptance-test-lbaas
    periodic:
      jobs:
        - terraform-provider-openstack-unittest
        - terraform-provider-openstack-acceptance-test
