name: functional-containerinfra
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - '.github/workflows/functional-containerinfra.yml'
      - 'go.mod'
      - 'openstack/**containerinfra**'
      - 'CHANGELOG.md'
      - 'scripts/*'
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: read
jobs:
  functional-containerinfra:
    strategy:
      fail-fast: false
      matrix:
        name: ["master"]
        openstack_version: ["master"]
        ubuntu_version: ["24.04"]
        include:
          - name: "master"
            openstack_version: "master"
            ubuntu_version: "24.04"
            devstack_conf_overrides: |
              enable_plugin magnum https://github.com/openstack/magnum master
              MAGNUMCLIENT_BRANCH=master
            additional_services: "openstack-cli-server"
          - name: "flamingo"
            openstack_version: "stable/2025.2"
            ubuntu_version: "24.04"
            devstack_conf_overrides: |
              enable_plugin magnum https://github.com/openstack/magnum stable/2025.2
              MAGNUMCLIENT_BRANCH=stable/2025.2
            additional_services: ""
          - name: "epoxy"
            openstack_version: "stable/2025.1"
            ubuntu_version: "24.04"
            devstack_conf_overrides: |
              enable_plugin magnum https://github.com/openstack/magnum stable/2025.1
              MAGNUMCLIENT_BRANCH=stable/2025.1
            additional_services: ""
          - name: "dalmatian"
            openstack_version: "stable/2024.2"
            ubuntu_version: "22.04"
            devstack_conf_overrides: |
              enable_plugin magnum https://github.com/openstack/magnum stable/2024.2
              MAGNUMCLIENT_BRANCH=stable/2024.2
            additional_services: ""
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Magnum on OpenStack ${{ matrix.name }}
    steps:
      - name: Checkout TPO
        uses: actions/checkout@v4
      - name: Deploy devstack
        uses: gophercloud/devstack-action@v0.19
        with:
          branch: ${{ matrix.openstack_version }}
          conf_overrides: |
            enable_plugin barbican https://github.com/openstack/barbican ${{ matrix.openstack_version }}
            enable_plugin heat https://github.com/openstack/heat ${{ matrix.openstack_version }}
            GLANCE_LIMIT_IMAGE_SIZE_TOTAL=5000
            SWIFT_MAX_FILE_SIZE=5368709122
            KEYSTONE_ADMIN_ENDPOINT=true

            ${{ matrix.devstack_conf_overrides }}
          enabled_services: "barbican-svc,barbican-retry,barbican-keystone-listener,h-eng,h-api,h-api-cfn,h-api-cw,${{ matrix.additional_services }}"
      - name: Checkout go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run TPO acceptance tests
        run: OS_CONTAINER_INFRA_ENVIRONMENT=true ./scripts/acceptancetest.sh
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          ACCEPTANCE_TESTS_FILTER: "containerinfra"
      - name: Generate logs on failure
        run: ./scripts/collectlogs.sh
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: functional-containerinfra-${{ matrix.name }}
          path: /tmp/devstack-logs/*
