# Functional testing for fwaas_v2
name: functional-fwaas_v2
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - '.github/workflows/functional-fwaas.yml'
      - 'go.mod'
      - 'openstack/**_fw_**'
      - '!**v1**'
      - 'CHANGELOG.md'
      - 'scripts/*'
  schedule:
    - cron: '0 0 */3 * *'
permissions:
  contents: read
jobs:
  functional-basic:
    strategy:
      fail-fast: false
      matrix:
        name: ["master"]
        openstack_version: ["master"]
        ubuntu_version: ["22.04"]
        include:
          - name: "epoxy"
            openstack_version: "stable/2025.1"
            ubuntu_version: "22.04"
          - name: "dalmatian"
            openstack_version: "stable/2024.2"
            ubuntu_version: "22.04"
          - name: "caracal"
            openstack_version: "stable/2024.1"
            ubuntu_version: "22.04"
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: fwaas on OpenStack ${{ matrix.name }}
    steps:
      - name: Checkout TPO
        uses: actions/checkout@v4
      - name: Deploy devstack
        uses: gophercloud/devstack-action@v0.19
        with:
          branch: ${{ matrix.openstack_version }}
          conf_overrides: |
            enable_plugin neutron-fwaas https://opendev.org/openstack/neutron-fwaas ${{ matrix.openstack_version }}
            Q_AGENT=openvswitch
            Q_ML2_PLUGIN_MECHANISM_DRIVERS=openvswitch,l2population
            Q_ML2_PLUGIN_TYPE_DRIVERS=flat,gre,vlan,vxlan
            Q_ML2_TENANT_NETWORK_TYPE=vxlan
            Q_TUNNEL_TYPES=vxlan,gre
          enabled_services: 'q-svc,q-agt,q-dhcp,q-l3,q-meta,q-fwaas-v2,-cinder,-horizon,-tempest,-swift,-c-sch,-c-api,-c-vol,-c-bak,-ovn,-ovn-controller,-ovn-northd,-q-ovn-metadata-agent'
      - name: Checkout go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run TPO acceptance tests
        run: OS_FW_ENVIRONMENT="1" ./scripts/acceptancetest.sh
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          ACCEPTANCE_TESTS_FILTER: "^.*FW.*V2.*$"
          OS_BRANCH: ${{ matrix.openstack_version }}
      - name: Generate logs on failure
        run: ./scripts/collectlogs.sh
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: functional-fwaas_v2-${{ matrix.name }}
          path: /tmp/devstack-logs/*
