name: Markdown-lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  markdown-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: '**/*.md'
          config: '.github/.markdownlint-cli2.jsonc'
